### ISSUE TITLE
nova-extension-schema glitches

### ISSUE THREAD

**Issue by kopischke** [apexskier/nova-json-language-server#1]
I’ve been using your JSON LSP extension for Nova on a Nova extension I am developing and have noticed it includes a schema for the `extension.json` file. First, thanks for creating this, it really is tremendously useful. However, it _does_ have a few kinks I’d love to see ironed out:

1. [**Option sections**](https://github.com/apexskier/nova-json-language-server/blob/9a558a7aba2cfc1c7ae08b7d2e368e043805ab2d/json.novaextension/nova-extension-schema.json#L414-L417) are incorrectly defined as containing a single `configItem` object. That should be an array of the same.
2. [**Enum item values**](https://github.com/apexskier/nova-json-language-server/blob/9a558a7aba2cfc1c7ae08b7d2e368e043805ab2d/json.novaextension/nova-extension-schema.json#L438-L442) are incorrectly defined as being exclusively of type string; in fact, they can also be a tuple of strings `[value, displayName]`, as per [Nova documentation](https://docs.nova.app/extensions/preferences/#enum-values).
3. [**The `message` property of an issueMatcher**](https://github.com/apexskier/nova-json-language-server/blob/9a558a7aba2cfc1c7ae08b7d2e368e043805ab2d/json.novaextension/nova-extension-schema.json#L474-L477) is incorrectly defined as being of type string; it is, in fact, of type number (and needs to be, as it is a capture group).
4. [**The `loop` property of an issueMatcher**](https://github.com/apexskier/nova-json-language-server/blob/9a558a7aba2cfc1c7ae08b7d2e368e043805ab2d/json.novaextension/nova-extension-schema.json#L507-L510) is not marked as optional; even [Panic’s own example code](https://docs.nova.app/extensions/issue-matchers/) omits it, and I can confirm issue matchers work just fine without it.

**Comment by apexskier** [comment]
Thanks! I'd definitely appreciate a PR to address these issues.

**Comment by kopischke** [comment]
I’d have loved to submit one, had I been able to do so. Unluckily, I must admit being utterly baffled by the JSON Schema specification (is it just me or is that thing unbelievably convoluted and verbose? Wasn’t JSON widely adopted because XML was considered too much so?). Sorry!

**Comment by kopischke** [comment]
… and now, of course, I can’t stop thinking about how I should be able to handle JSON Schema, what with me being a big boy who read and (mostly) understood the _SGML Handbook_, back in the days. Gah. I’ll give it a try.

**Comment by kopischke** [comment]
Note to self: less whining, more searching of SO next time.
