### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by gingerbeardman** [apexskier/nova-json-language-server#108]
**To reproduce**

1. using Nova 6.0
2. Follow link from extensions website
3. When in Nova, click install

**Expected behavior**

Should install without error

**Screenshots**

<img width="460" alt="Screen shot 2021-04-22 at 11 39 17" src="https://user-images.githubusercontent.com/49612/115701310-914e9900-a35f-11eb-9bee-e5aef1fe7311.png">

**Environment**

- Nova version: 6.0 (Build 267401)
- Extension version: 1.1.0
- macOS version: 10.14.6 (18G8022)
- NodeJS information:
  - node version:
```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
[1]    74028 abort      node --version
```
  - npm version: 7.7.6
  - installation method: via Nova extension library

**Solution**

I reinstalled/upgraded node using `homebrew`

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
