### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by fm** [apexskier/nova-json-language-server#321]
**To reproduce**

When editing the json file, Nova is not prompting me to autocomplete the fields, while VSCode does. I have a `package.json` and `schema.json` file.

I do notice VSCode has a `settings.json` file in the `.vscode` folder that may be the one being fetched for the autocomplete.

```
{
    "files.eol": "\n",
    "[json]": {
        "editor.formatOnSave": false,
        "editor.formatOnPaste": false
    },
    "json.schemas": [
        {
            "fileMatch": ["/companies/*.json"],
            "url": "./schema.json"
        },
        {
            "fileMatch": ["/supervisory-authorities/*.json"],
            "url": "./schema-supervisory-authorities.json"
        },
        {
            "fileMatch": ["/company-packs/*.json"],
            "url": "./schema-company-packs.json"
        }
    ]
}
```

**Expected behavior**

It was my impression this extension would help me replicate the VSCode behavior, if not, I'll close this issue!

**Screenshots**

*VSCode:*
![image](https://user-images.githubusercontent.com/3654256/232300272-7f314aae-61c1-4469-a5b9-c6ea3f9ea1df.png)

![image](https://user-images.githubusercontent.com/3654256/232300274-212942b9-4a51-45f5-a034-e01db61b0d35.png)

*Nova*
![image](https://user-images.githubusercontent.com/3654256/232300414-9538abaa-4ee7-4806-a202-e267a9c55c90.png)

![image](https://user-images.githubusercontent.com/3654256/232300431-1c5bb191-508c-42eb-954b-15e60e33793d.png)

This is the only autocomplete that pops up in Nova

![image](https://user-images.githubusercontent.com/3654256/232300917-a9967bee-a3f5-4dab-89d2-7144f883fd67.png)

**Environment**

- Nova version: 10.6 (476615)
- Extension version: 1.1.1
- macOS version: 13.3.1 (22E261)
- NodeJS information:
  - node version: v19.8.1
  - npm version: 9.5.1
  - installation method: installer

**Extension console output**

```JSON[12:32:31.316000] activating...

JSON[12:32:31.318000] claimed lock

JSON[12:32:31.518000] installing: npm WARN old lockfile

JSON[12:32:31.519000] installing: npm WARN old lockfile The npm-shrinkwrap.json file was created with an old version of npm,

JSON[12:32:31.519000] installing: npm WARN old lockfile so supplemental metadata must be fetched from the registry.

JSON[12:32:31.520000] installing: npm WARN old lockfile

JSON[12:32:31.520000] installing: npm WARN old lockfile This is a one-time fix-up, please be patient...

JSON[12:32:31.522000] installing: npm WARN old lockfile

JSON[12:32:32.444000] installing: 

JSON[12:32:32.444000] installing: up to date in 962ms

JSON[12:32:32.449000] clearing lock

JSON[12:32:32.459000] activated

JSON[12:32:34.020000] registered schemas
```

**Additional context**

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
