### ISSUE TITLE
rogue, unwarranted npn error upon install / every launch

### ISSUE THREAD

**Issue by pixeled** [apexskier/nova-json-language-server#389]
This is a JSON extension-

That’s all I want. I’m an iOS/MacOS developer.

I installed this extension, and immediately get this alert.

<img width="447" alt="Screen 2023-12-15 at 10 41 57 AM" src="https://github.com/apexskier/nova-json-language-server/assets/355899/ab132998-885f-4ccb-bcb4-3375645e30d8">

Is there anyway to turn this off?

Is it going to affect the functioning of this extension?

**Comment by apexskier** [comment]
This is just how the extension works. [It runs the](https://github.com/apexskier/nova-json-language-server#json-support-for-nova) [vscode-json-languageserver](https://www.npmjs.com/package/vscode-json-languageserver) internally, which is a node program.

You'll need a valid node/npm install to use it, as currently designed, or it would have to install one for you.
